# Generated by Django 2.2 on 2020-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='用户名', max_length=20)),
                ('sex', models.IntegerField(blank=True, choices=[('0', '男'), ('1', '女')], help_text='性别', null=True)),
                ('password', models.CharField(help_text='密码', max_length=32)),
            ],
        ),
    ]
